name: Generate Documentation

on:
  push:
    branches: ['main']
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate docs
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: tabs-vs-spaces
          description: Hint and fix deviating indentation.
          version: 'Neovim >= 0.8.0'
          demojify: true
      - name: Commit docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: auto generate vim docs'
          branch: ${{ github.head_ref }}
